package de.thb.mps.tanni.Junit4_5.sandbox;

/*Generated by MPS */

import rob.testproject.Rechner;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Assertions;

public class RechnerTest {

  private Rechner underTest;


  @BeforeEach
  public void setUp() throws Exception {
    underTest = new Rechner();
  }

  @Test
  @DisplayName("Testet die Addition von 4 und 4. Das Ergebnis ist 8")
  public void addierenTest() {
    int expected_result_a = 8;
    int result = underTest.addieren(4, 4);
    Assertions.assertEquals(expected_result_a, result);
  }
  @Test
  @DisplayName("Testet die Substraktion von 5 und 3. Das Ergbenis ist 2")
  public void substrahierenTest() {
    int expected_result_b = 2;
    int result = underTest.substrahieren(5, 3);
    Assertions.assertEquals(expected_result_b, result);
  }
  @Test
  @DisplayName("Testet die Multiplikation von 4 und 4. Das Ergebnis ist 16")
  public void multiplizierenTest() {
    int expected_result_c = 16;
    int result = underTest.multiplizieren(4, 4);
    Assertions.assertEquals(expected_result_c, result);
  }
  @Test
  @DisplayName("1")
  public void dividierenTest() {
    int expected_result_d = 1;
    int result = underTest.dividieren(4, 4);
    Assertions.assertEquals(expected_result_d, result);
  }
}
