package de.thb.mps.tanni.Junit4_5.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int EqualAssert = 0;
  public static final int Test = 1;
  public static final int TestCase = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x95866216e5aa493fL, 0xbb273c6c8066e765L);
    builder.put(0xa9e170e92b23b5fL, EqualAssert);
    builder.put(0xa9e170e92b24488L, Test);
    builder.put(0xa9e170e92b27b79L, TestCase);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
