package de.thb.mps.tanni.Junit4_5.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new EqualAssert_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Test_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new TestCase_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x95866216e5aa493fL, 0xbb273c6c8066e765L, 0xa9e170e92b23b5fL), MetaIdFactory.conceptId(0x95866216e5aa493fL, 0xbb273c6c8066e765L, 0xa9e170e92b24488L), MetaIdFactory.conceptId(0x95866216e5aa493fL, 0xbb273c6c8066e765L, 0xa9e170e92b27b79L)).seal();
}
